baseURL = 'https://whoreganizer.blog'
languageCode = 'en-us'
title = "Whoreganizer"
theme = 'archie'

[params]
  mode='dark'

[[params.assets]]
favicon = "/favicon.ico"
favicon16x16 = "/favicon-16x16.png"
favicon32x32 = "/favicon-32x32.png"
apple_touch_icon = "/apple-touch-icon.png"

[[params.social]]
name = 'Twitter'
icon = 'twitter'
url = 'https://twitter.com/whoreganizer'

[[menu.main]]
name = 'All Posts'
url = '/posts'
weight = 1
