baseURL = 'https://whoreganizer.blog'
languageCode = 'en-us'
title = "Whoreganizer"
theme = 'archie'

[params]
  mode='dark'

[[params.assets]]
favicon = "/icons8-umbrella-pixels-16.png"
favicon16x16 = "/icons8-umbrella-pixels-16.png"
favicon32x32 = "/icons8-umbrella-pixels-16.png"
apple_touch_icon = "/icons8-umbrella-pixels-60.png"


[[params.social]]
name = 'Twitter'
icon = 'twitter'
url = 'https://twitter.com/whoreganizer'

[[menu.main]]
name = 'All Posts'
url = '/posts'
weight = 1
